spring:
  application:
    name: xgChatServer
  cloud:
    nacos:
      discovery:
        server-addr: 124.222.121.252:8848
        namespace: db3d5d0c-8625-4b26-858b-c852544930f5
        username: nacos
        password: xugang1998
server:
  port: 9898