spring:
  application:
    name: xgChatServer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.222.121.252:3306/xgchat
    username: root
    password: xugang1998
  cloud:
    nacos:
      discovery:
        server-addr: 124.222.121.252:8848
        namespace: db3d5d0c-8625-4b26-858b-c852544930f5
        username: nacos
        password: xugang1998
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  mapper-locations: classpath:/mapper/*.xml
server:
  port: 9898